
auth.token=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

defaults.org=luizinhos-house
defaults.project=react-native

defaults.url=https://sentry.io/
