defaults.url=https://sentry.io/
defaults.org=luizinhos-house
defaults.project=react-native
# Using SENTRY_AUTH_TOKEN environment variable
auth.token=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
